### ISSUE TITLE
workflow validation

### ISSUE THREAD

**Issue by EEngl52** [OCR-D/taverna_workflow#2]
ocrd-process first validates the input/output filegroups before it actually starts to process the data in the workspace. As Taverna currently lacks this kind of validation, it might fail in the middle of a workflow due to e.g. a typo in an input filegroup. 

Would be great if Taverna could provide a similar validation as ocrd-process.

**Comment by kba** [comment]
It could just use the `ocrd process` validation directly, using `ocrd validate tasks` which will produce an XML(-ish) validation report like all other validation routines.
